export {default as colores} from './colores.route'
export {default as configuracion} from './configuracion.route'
export {default as rubrosRoutes} from './rubros.route'
export {default as productos} from './producto.route'
export {default as subrubrosRoutes} from './subRubros.route'
export { default as varianteProducto} from './varianteProducto.route'