services:
  api-libreria:
    build:
      context: .
      dockerfile: dockerfile

    container_name: api-libreria
    ports:
      - "${PORT_LOCAL}:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - BASE_URL=${BASE_URL}
      - PORT=${PORT}
    volumes:
      - .cert:/cert/cert
    restart: always
